name: Deploy Application

on:
  push:
    branches:
      - main
    paths:
      - "app.py"
      - ".github/workflows/deploy.yml"
      - "templates/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Connect to EC2 Instance
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_DEPLOY_KEY }}
          script: |
            cd ~/DevOps-Workshop

            # Write .env file with GitHub Secrets
            cat <<EOF > .env
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            EOF

            git pull origin main
            sudo systemctl enable flask-app.service
            sudo systemctl restart flask-app.service
            sudo systemctl status flask-app.service --no-pager
