name: Ruff Code Linting

on:
  pull_request:
    branches: [dev]

jobs:
  ruff-lint:
    name: Ruff Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ruff
        run: pip install ruff
        
      - name: Run Ruff
        run: |
          ruff check . 

